version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: 1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase
      UVICORN_PORT: 8080
      ENV: dev
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: langtutor
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
