version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: 1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://polyglot:mysecretpassword@db:5432/polyglot
      UVICORN_PORT: 8080
      ENV: dev
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: polyglot
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: polyglot
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
