version: '3'

services:
  web:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: langtutor
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
