"""Add soft delete to ChatSession.

Revision ID: 10cad7b41e18
Revises: ac3830b9b3f9
Create Date: 2023-06-27 13:32:39.662841

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '10cad7b41e18'
down_revision = 'ac3830b9b3f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'deleted_at')
    # ### end Alembic commands ###
