"""Rename locale to language.

Revision ID: 3a0a3b54cd34
Revises: fa239b127e58
Create Date: 2023-07-19 09:57:02.177496

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3a0a3b54cd34'
down_revision = 'fa239b127e58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(length=5), nullable=False))
    op.drop_column('user', 'locale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('user', 'language')
    # ### end Alembic commands ###
