"""Add chat session and tutor.

Revision ID: 89fb951baae7
Revises: e90f5b08ab97
Create Date: 2023-06-19 14:04:54.664318

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89fb951baae7'
down_revision = 'e90f5b08ab97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tutor',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('visible', sa.Boolean(), nullable=False),
        sa.Column('language', sa.String(), nullable=False),
        sa.Column('system_prompt', sa.String(), nullable=False),
        sa.Column('personality_prompt', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('tutor_pkey')),
    )
    op.create_table(
        'chat_session',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'message_history',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=text("'[]'::jsonb"),
        ),
        sa.Column('max_tokens', sa.Integer(), nullable=False),
        sa.Column('max_messages', sa.Integer(), nullable=False),
        sa.Column('tutor_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], name=op.f('chat_session_tutor_id_fkey')),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chat_session_user_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('chat_session_pkey')),
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('locale', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('chat_session')
    op.drop_table('tutor')
    # ### end Alembic commands ###
