"""New User model for Firebase auth.

Revision ID: c79ffb48c9bb
Revises: 10cad7b41e18
Create Date: 2023-07-09 16:33:20.617789

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c79ffb48c9bb'
down_revision = '10cad7b41e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('oauth_account_account_id_idx', table_name='oauth_account')
    op.drop_index('oauth_account_oauth_name_idx', table_name='oauth_account')
    op.drop_table('oauth_account')
    op.add_column('user', sa.Column('firebase_uid', sa.String(length=128), nullable=False))
    op.create_index(op.f('user_firebase_uid_idx'), 'user', ['firebase_uid'], unique=True)
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('user_firebase_uid_idx'), table_name='user')
    op.drop_column('user', 'firebase_uid')
    op.create_table(
        'oauth_account',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('oauth_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('access_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('refresh_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.Column('account_id', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
        sa.Column('account_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='oauth_account_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='oauth_account_pkey'),
    )
    op.create_index('oauth_account_oauth_name_idx', 'oauth_account', ['oauth_name'], unique=False)
    op.create_index('oauth_account_account_id_idx', 'oauth_account', ['account_id'], unique=False)
    # ### end Alembic commands ###
