"""Only name for user..

Revision ID: fa239b127e58
Revises: c79ffb48c9bb
Create Date: 2023-07-17 17:11:56.716794

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fa239b127e58'
down_revision = 'c79ffb48c9bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
